sub = ""
spec = ""
lab = ""
variant = ""
labs = {"Основи програмування": "OP"}
price_list = { "Основи програмування" : 10 }
monobank_link = 'https://send.monobank.ua/pMCrQEzQE'
payment_channel_id = -1001703135845
TUNNEL_URL = "https://labhub-bot-tatkmdbnbq-ez.a.run.app"